
box = precise64
box_url = http://files.vagrantup.com/precise64.box

init:
	vagrant init ${box} ${box_url}

init-url:
	vagrant init ${box} ${box_url}

up:
	vagrant up

ssh:
	vagrant ssh

destory:
	vagrant destroy

status:
	vagrant gabal-status

add-box:
	vagrant box add ${box}

remove-box:
	vagrant box remove ${box}
