# https://archive.ics.uci.edu/ml/datasets/auto+mpg
#
# download data files
init:
	curl -s https://raw.githubusercontent.com/curran/d3-in-motion/master/data/cars.csv -o cars-data.csv

# run node webserver
run:
	live-server



